# Site settings
title: theWhiteFox Web UI Dev
email: ste@theWhiteFox.ninja
description: > # this means to ignore newlines until "baseurl:"
  Stephen Ã“ Connor theWhiteFox Web UI Developer JS HTML5 CSS3 PHP Ruby Java.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://thewhitefox.github.io" # the base hostname & protocol for your site
twitter_username: steTheWhiteFox
github_username:  theWhiteFox

# Build settings
markdown: kramdown

exclude:
  - package.json
  - node_modules
  - gulpfile.js

keep_files:
  - _site/css
  - _site/js

include: ['_pages']
